# Generated by Django 5.1.7 on 2025-03-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assigned_to',
        ),
    ]
